/*
 * Copyright (C) 2009-2014 SAP SE or an SAP affiliate company. All rights reserved
 */
jQuery.sap.declare("PD.TotalCompStatement.controls.PDFViewer");jQuery.sap.require("sap.ui.core.library");jQuery.sap.require("sap.ui.core.RenderManager");sap.ui.core.Control.extend("PD.TotalCompStatement.controls.PDFViewer",{metadata:{properties:{"src":{type:"string",group:"Misc"},"errorMessage":{type:"string",group:"Misc"},"setPdfData":{type:"string",group:"Misc"}},events:{"begin":{},"complete":{}}}});
PD.TotalCompStatement.controls.PDFViewer.prototype.exit=function(){jQuery.sap.log.debug("exit "+this.getSrc());this.UnloadPdf();this.ClearPdfData();};
PD.TotalCompStatement.controls.PDFViewer.prototype.Show=function(l){var s=this.getSrc();if(s==null||s.length==0){return;}if(!this._pdfData){this.fireBegin();l.LoadPdf(s,jQuery.proxy(this.setPdfData,this),jQuery.proxy(this.showErrorMessage,this));}else{this.RenderPdf();}};
PD.TotalCompStatement.controls.PDFViewer.prototype.ClearPdfData=function(){this._pdfData=null;};
PD.TotalCompStatement.controls.PDFViewer.prototype.UnloadPdf=function(){if(this._pdf!=null){jQuery.sap.log.debug("UnloadPdf "+this.getSrc());this._pdf.destroy();this._pdf=null;$(this.getDomRef()).empty();}};
PD.TotalCompStatement.controls.PDFViewer.prototype.setPdfData=function(d){this._pdfData=d;this.RenderPdf();};
PD.TotalCompStatement.controls.PDFViewer.prototype.showErrorMessage=function(r){var e=(r!=null)?null:JSON.parse(r);};
PD.TotalCompStatement.controls.PDFViewer.prototype.RenderPdf=function(){var i=this.getDomRef(),t=this,c=[];jQuery.sap.log.debug("RenderPdf "+this.getSrc());if(i.childNodes!=null&&i.childNodes.length>0){setTimeout(function(){jQuery.sap.log.debug("The control is already rendered");t.fireComplete();},500);return;}var p=jQuery.sap.getModulePath("hcm.mypaystubs")+"/ext/pdfjs/pdf.js";jQuery.sap.require("hcm.mypaystubs.ext.pdfjs.pdf");if(PDFJS.workerSrc!=p){PDFJS.workerSrc=p;}PDFJS.getDocument(this._pdfData).then(function getPdfForm(a){t._pdf=a;var v=i,b=1;t.renderPage(v,a,b++,function pageRenderingComplete(){if(b>a.numPages){jQuery.sap.log.debug("renderPage complete");t.fireComplete();return;}jQuery.sap.log.debug("render another page");t.renderPage(v,a,b++,pageRenderingComplete);},c);});};
PD.TotalCompStatement.controls.PDFViewer.prototype.renderPage=function(d,p,a,c){p.getPage(a).then(function(b){jQuery.sap.log.debug("renderingPage "+a);var e,v,f,g,s,h;s=2;if(d.offsetParent==null||d.offsetParent.clientWidth==null){jQuery.sap.log.debug("invalid offsetParent");return;}e=d.offsetParent.clientWidth;v=b.getViewport(1);f=v.width;g=jQuery.device.is.phone?1:e/f;h=b.getViewport(s*g);var i=h.width;var j=h.height;var k=document.createElement('div');k.className='pdfpage';if(jQuery.device.is.phone){k.style.width=i+'px';k.style.height=j+'px';}else{k.style.width=i/s+'px';k.style.height=j/s+'px';}d.appendChild(k);var l=document.createElement('canvas');var m=l.getContext('2d');l.width=i;l.height=j;if(jQuery.device.is.phone){l.style.width=i+'px';l.style.height=j+'px';}else{l.style.width=i/s+'px';l.style.height=j/s+'px';}var r={canvasContext:m,viewport:h};b.render(r).then(function(){k.appendChild(l);c();});});};